---
title: "Ruan van Mazijk, *Curriculum vitae*"
subtitle: "MSc candidate, Dept. of Biological Sciences, University of Cape Town"
author: "<ruanvmazijk@gmail.com>, +27 72 516 7570, [rvanmazijk.github.io](https://rvanmazijk.github.io)"
output:
  pdf_document:
    latex_engine: xelatex
mainfont: Avenir
linkcolor: blue
urlcolor: blue
---

I am curiosity driven, interested in plant & animal phylogenetics & systematics, community ecology, plant ecophysiology, & the effects of climate change on the world's biota. I enjoy applying numerically & statistically grounded methods in these fields. My long-term goals are careers in research, academia, & teaching.

# Education

MSc candidate (UCT) (2018--present), on _The effects of genome size on plant hydraulic ecophysiology, habitat & phenology in Cape Schoenoid sedges (Cyperaceae: Schoeneae)_. Principle supervisor: A/Prof A.M. Muasya. Co-supervisors: A/Prof G.A. Verboom & A/Prof A.G. West.

BSc Hons in Biological Sciences (UCT) (2017), on _The role of environmental heterogeneity in determining plant species richness in the Greater Cape Floristic Region & the Southwest Australia Floristic Region_. Supervisors: A/Prof M.D. Cramer & A/Prof G.A. Verboom. Graduated with distinction.

BSc (UCT) (2016). Majors: Ecology & Evolution, Applied Biology. Distinction in both majors & the degree as a whole.

# Publications

Cramer, M.D., van Mazijk, R., Wootton, L.M., Verboom, G.A. (In prep.). Edaphic diversity in a global biodiversity hotspot.

Van Mazijk, R., Cramer, M.D., Verboom, G.A. (In prep.). The role of environmental heterogeneity in determining plant species richness in the Greater Cape Floristic Region & the Southwest Australia Floristic Region.

Van Mazijk, R., Smythe, L.K., Weideman, E.A., West, A.G. (In review). Isotopic tracing of storm-water in the urban Liesbeek River. _Water SA_.

# Professional affiliations

South African Association of Botanists (SAAB) member (2017--present).

Southern African Society for Systematic Biology (SASSB) (2018--present).

Golden Key International Honour Society member (2015--present).

# Funding & awards

## Scholarships & bursaries

South African Association of Botanists (SAAB) MSc Student Bursary (inaugural recipient) (R20,000 p.a.) (2018, 2019).

Dorothy Cameron Scholarship (R20,000 p.a.) (2018).

UCT Masters Research Scholarship (R25,000 p.a.) (2018).

DST-NRF Innovation Honours Scholarship (R60,000 p.a.) (2017).

South African Association of Botanists (SAAB) Honours Scholarship (R10,000 p.a.) (2017).

UCT Science Faculty Scholarship (R15,000 p.a.) (2015, 2016).

## Awards & honours

Dick & Dorothy Borcherds Prize (R1,000 p.a.) (UCT) (2015).

Dean's Merit List (UCT) (2014--2016).

Class Medals (top of the class) for five Biological Sciences undergraduate courses (UCT) (2014--2016).

# Leadership experience

Departmental Representative for the Dept. of Biological Sciences (UCT) (2016).

Class Representative for three Biological Sciences undergraduate courses (UCT) (2015--2016).

# Teaching

Assistant tutor for short course _SEEC-ACCESS Introduction to statistical modelling & data analysis_ (18--20 July 2018). Organiser: A/Prof R. Altwegg (UCT).

Tutor for _Study Design & Data Analysis for Scientists_ (STA2007F/S/H) (UCT) (2017--present). Convenor: A/Prof R. Altwegg (UCT).

Assistant tutor for _Bionumeracy_ (STA1007S) R practicals (UCT) (2016--present). Convenor: A/Prof R. Altwegg (UCT).

Hot-seat tutor for _Mathematics for Biology, Earth, & Environmental Sciences_ (MAM1004F/S) (UCT) (2015). Convenor: T. van Heerden. Hot-seat organiser: Dr R. Moolman.

# Skills

Extended experience with Apple macOS, MS Windows, MS Office, R, RMarkdown, Git, GitHub.

Fluent in both English & Afrikaans.

Animal Ethics Course (South African Veterinary Council) (part of BSc Hons) (2017-04).

# References

Associate Prof R. Altwegg

- Dept. of Statistical Sciences, UCT
- Head of Centre for Statistics in Ecology, the Environment and Conservation (SEEC)
- <res.altwegg@uct.ac.za>
- +27 21 650 5750

Prof T.A. Hedderson

- Dept. of Biological Sciences, UCT
- <terry.hedderson@uct.ac.za>
- +27 21 650 4037
