---
output: 
  pdf_document:
    latex_engine: xelatex
mainfont: Avenir
geometry: margin=1cm
header-includes:
  # Set font size here, as `fontsize:` doesn't work w/ custom `mainfont:`
  - \usepackage[fontsize=10pt]{scrextend}
---

\pagenumbering{gobble} <!--turns off page numbering-->

# Ruan van Mazijk, _Curriculum vitae_ \hfill <ruanvmazijk@gmail.com>, +27 72 516 7570<!--, [rvanmazijk.github.io](https://rvanmazijk.github.io)-->

## Education

- **MSc candidate in Biological Sciences** _Cape Town_ \hfill 2018--present
  \par Dissertation title: _Genome size effects on plant hydraulic ecophysiology, habitat & phenology_
  \par \ \ \ \ _in Cape Schoenoid sedges (Cyperaceae: Schoeneae)_
  \par Principle supervisor: A/Prof A.M. Muasya. Co-supervisors: A/Prof G.A. Verboom & A/Prof A.G. West
- **BSc Hons in Biological Sciences** _Cape Town_ \hfill 2017
  \par Graduated with distinction. Dissertation title: _Relating vascular plant species richness & environmental heterogeneity_
  \par \ \ \ \ _across spatial scales in the Greater Cape Floristic Region & the Southwest Australia Floristic Region_
  \par Supervisors: Prof M.D. Cramer & A/Prof G.A. Verboom
- **BSc in Ecology & Evolution, Applied Biology** _Cape Town_ \hfill 2016
  \par Distinction in both majors & the degree as a whole

## Publications

- Elliott, T.L., Laidler, G., Muasya, A.M., Muthaphuli, N. & **van Mazijk, R.** (In review). Foregrounding sedges: bringing the neglected Cape Schoenoid sedges to the forefront of genomic research. _Veld & Flora_.
- Cramer, M.D., Wootton, L.M., **van Mazijk, R.** & Verboom, G.A. (In review). Improved spatial soil data confirms dependence of vegetation distribution on edaphic properties in the Cape biodiversity hotspot. _Diversity & Distributions_.
- **Van Mazijk, R.**, Cramer, M.D. & Verboom, G.A. (In prep.). The role of environmental heterogeneity in determining plant species richness in the Greater Cape Floristic Region & the Southwest Australia Floristic Region. _Journal of Biogeography_.
- **Van Mazijk, R.**, Smythe, L.K., Weideman, E.A. & West, A.G. (2018). Isotopic tracing of stormwater in the urban Liesbeek River. _Water SA_, 44(4):674--679. DOI: [10.4314/wsa.v44i4.16](http://dx.doi.org/10.4314/wsa.v44i4.16).

## Professional affiliations

- Council member, Student Representative Portfolio, Southern African Society for Systematic Biology (SASSB) \hfill 2019--present
- Student member, South African Association of Botanists (SAAB) \hfill 2017--present

## Funding & awards

- SASSB Best MSc Presentation (3-way tie), at the 45^th^ Annual SAAB, AMA & SASSB Joint Congress \hfill January 2019
- DST-NRF Innovation Masters Scholarship (R90,000) \hfill 2019
- SAAB MSc Student Bursary (inaugural recipient) (R20,000) \hfill 2018, 2019
- UCT Once-Off Top Up Award (R5,520) \hfill 2018
- UCT Conference Travel Grant to attend the 45^th^ Annual SAAB, AMA & SASSB Joint Congress, 2019 (R3,819) \hfill 2018
- UCT Dept. of Biological Sciences Dorothy Cameron Scholarship (R20,000) \hfill 2018
- UCT Masters Research Scholarship (R30,000) \hfill 2018
- DST-NRF Innovation Honours Scholarship (R60,000) \hfill 2017
- SAAB Honours Scholarship (R10,000) \hfill 2017
- UCT Science Faculty Scholarship (R15,000 p.a.) \hfill 2015, 2016
- Dick & Dorothy Borcherds Prize for the highest standard in 2^nd^ year biology (R1,000) \hfill 2015

## Teaching experience

- Teaching assistant for undergraduate angiosperm diversity practicals \hfill 2018--present
- Tutor for undergraduate study design & data analysis for scientists \hfill 2017--present
- Assistant tutor for short course _SEEC-ACCESS Introduction to statistical modelling & data analysis_ \hfill 18--20 July 2018
- Assistant tutor for undergraduate R practicals \hfill 2016--present
- Hot-seat tutor for mathematics for biology, earth & environmental sciences undergraduates \hfill 2015

## References

- A/Prof G.A. Verboom, Dept. of Biological Sciences & Bolus Herbarium, UCT \hfill <tony.verboom@uct.ac.za>, +27 21 650 3398
- Prof M.D. Cramer, Dept. of Biological Sciences, UCT \hfill <michael.cramer@uct.ac.za>, +27 21 650 2444
